# Generated by Django 3.2.16 on 2024-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название повода'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='Слаг'),
        ),
    ]
